### ISSUE TITLE
double click on play throws

### ISSUE THREAD

**Issue by frequent** [frequent/frube#40]
player.loadVideoById is not a function

Stack: TypeError: player.loadVideoById is not a function
    at https://frube.eu/gadget_frube.js:712:20
    at invokeCallback (https://frube.eu/rsvp.latest.js:581:19)
    at Promise.<anonymous> (https://frube.eu/rsvp.latest.js:650:11)
    at Promise.trigger (https://frube.eu/rsvp.latest.js:378:22)
    at https://frube.eu/rsvp.latest.js:737:17
    at https://frube.eu/rsvp.latest.js:189:11
    at Array.forEach (native)
    at MutationObserver.<anonymous> (https://frube.eu/rsvp.latest.js:187:19)

**Comment by frequent** [comment]
could not reproduce. This should mitigate (and may throw somewhere else) - 19a674832ad3f84a80c5543f414269c37bcb0bfe
