### ISSUE TITLE
there is an error behind the splash screen

### ISSUE THREAD

**Issue by frequent** [frequent/frube#70]
on mobile. try to reproduce when removing the splash screen

**Comment by frequent** [comment]
this one:
Unhandled Error
Please report this error to the support team

Location: https://frube.eu/#ziYhn_NzHNQ

User-agent: Mozilla/5.0 (X11; CrOS armv7l 10452.96.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Date: 2018-06-05T13:21:26.590Z

Cannot read property 'postMessage' of null
Stack: TypeError: Cannot read property 'postMessage' of null
    at https://frube.eu/jio.workerstorage.js:65:40
    at new Promise (https://frube.eu/rsvp.latest.js:560:9)
    at https://frube.eu/jio.workerstorage.js:34:14
    at invokeCallback (https://frube.eu/rsvp.latest.js:581:19)
    at Promise.<anonymous> (https://frube.eu/rsvp.latest.js:650:11)
    at Promise.trigger (https://frube.eu/rsvp.latest.js:378:22)
    at https://frube.eu/rsvp.latest.js:737:17
    at https://frube.eu/rsvp.latest.js:189:11
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (https://frube.eu/rsvp.latest.js:187:19)
stopping renderJS
Stack: Error: stopping renderJS
    at letsCrash (https://frube.eu/renderjs.latest.js:854:21)
    at RenderJSGadget.reportServiceError (https://frube.eu/renderjs.latest.js:2155:9)
    at https://frube.eu/renderjs.latest.js:1381:39
    at invokeCallback (https://frube.eu/rsvp.latest.js:581:19)
    at Promise.<anonymous> (https://frube.eu/rsvp.latest.js:650:11)
    at Promise.trigger (https://frube.eu/rsvp.latest.js:378:22)
    at https://frube.eu/rsvp.latest.js:737:17
    at https://frube.eu/rsvp.latest.js:189:11
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (https://frube.eu/rsvp.latest.js:187:19)

**Comment by frequent** [comment]
controller is not defined, the sw.ready promise seems to trigger before it actually is ready... any[sw.ready and a loop testing for sw.controller]?

**Comment by frequent** [comment]
https://gist.github.com/Rich-Harris/fd6c3c73e6e707e312d7c5d7d0f3b2f9
https://github.com/mozilla/serviceworker-cookbook/issues/170
https://github.com/w3c/ServiceWorker/issues/799
https://stackoverflow.com/questions/40161452/service-worker-controllerchange-never-fires
